DROP TABLE IF EXISTS user_activity;
DROP TABLE IF EXISTS user_restaurant;
DROP TABLE IF EXISTS user_drink;
DROP TABLE IF EXISTS activity;
DROP TABLE IF EXISTS drink;
DROP TABLE IF EXISTS restaurant;
DROP TABLE IF EXISTS user;
